"""Auth management CLI commands."""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

import typer

app = typer.Typer(help="Auth management commands.")


def _discover_database_url() -> str | None:
    """Return the project's database URL by importing its settings module.

    Searches the current directory for a package containing ``settings.py``
    with a ``get_settings()`` callable (the pattern generated by the scaffolder).
    """
    sys.path.insert(0, str(Path.cwd()))
    import importlib

    candidates = ["settings"] + [
        f"{p.name}.settings"
        for p in Path.cwd().iterdir()
        if p.is_dir() and not p.name.startswith(".") and not p.name.startswith("_") and (p / "settings.py").exists()
    ]
    for module_name in candidates:
        try:
            mod = importlib.import_module(module_name)
            get_settings = getattr(mod, "get_settings", None)
            if callable(get_settings):
                return get_settings().database_url  # type: ignore[no-any-return]
        except Exception:
            continue
    return None


async def _do_createsuperuser(email: str, password: str) -> None:
    from sqlalchemy.exc import IntegrityError

    from fast_agent_stack.core.auth.models import User
    from fast_agent_stack.core.auth.password import hash_password
    from fast_agent_stack.core.database import configure_engine, get_async_session

    database_url = _discover_database_url()
    if database_url is None:
        typer.echo(
            "Error: could not discover DATABASE_URL. "
            "Run from your project root and ensure settings.py defines get_settings().",
            err=True,
        )
        raise typer.Exit(1)

    configure_engine(database_url)
    async for session in get_async_session():
        user = User(
            email=email,
            password_hash=hash_password(password),
            is_active=True,
            is_verified=True,
            is_staff=True,
            is_superuser=True,
        )
        session.add(user)
        try:
            await session.commit()
        except IntegrityError:
            typer.echo(f"Error: A user with email '{email}' already exists.", err=True)
            raise typer.Exit(1)
        typer.echo(f"Superuser '{email}' created.")
        break


@app.command()
def createsuperuser(
    email: str | None = typer.Option(None, "--email", "-e", help="Superuser email."),
    password: str | None = typer.Option(
        None,
        "--password",
        "-p",
        help="Superuser password (prompted if omitted).",
    ),
) -> None:
    """Create a superuser account."""
    if email is None:
        email = typer.prompt("Email")
    if password is None:
        password = typer.prompt("Password", hide_input=True, confirmation_prompt=True)
    asyncio.run(_do_createsuperuser(email, password))
